--- 
apiVersion: v1
kind: Service
metadata: 
  name: d8-service
spec: 
  ports: 
    - name: http
      port: 80
      protocol: TCP
  selector: 
    app: d8-app
  type: LoadBalancer
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: d8-app
  name: d8-deploy
spec: 
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: d8-app
  template: 
    metadata: 
      labels: 
        app: d8-app
    spec: 
      initContainers:
        - name: init-sites-volume
          image: carmelopz/php-with-drupal-src:7.4-fpm-buster
          command: ['/bin/bash', '-c']
          args: ['cp -r /var/www/html/. /data; chown www-data:www-data /data/ -R']
          volumeMounts:
          - mountPath: /data
            name: vol-drupal
      containers: 
        - image: carmelopz/php-with-drupal-src:7.4-fpm-buster
          name: d8-php
          ports: 
            - containerPort: 9000
          volumeMounts:
          - mountPath: /var/www/html
            name: vol-drupal
        - image: carmelopz/nginx-drupal:1.19.1
          name: d8-nginx
          ports: 
            - containerPort: 80
          volumeMounts:
          - mountPath: /var/www/html
            name: vol-drupal
      volumes:
        - name: vol-drupal
          persistentVolumeClaim: 
            claimName: pvc-d8
