--- 
apiVersion: v1
kind: Service
metadata: 
  name: d8-mariadb
spec: 
  ports: 
    - name: mysql
      port: 3306
      protocol: TCP
  selector: 
    app: d8-mariadb
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: d8-mariadb
spec: 
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: d8-mariadb
  template: 
    metadata: 
      labels: 
        app: d8-mariadb
    spec:
      initContainers:
        
        - name: init-sqldump-volume
          image: mariadb:10.5.4
                  
          command: ['/bin/bash', '-c']
          args: ['apt update && apt install -y wget && wget https://github.com/carmelopz/drupal-kube-3tier-composer/raw/master/database/d8-umami-mysqldump.sql']
          
          volumeMounts:
          - mountPath: /docker-entrypoint-initdb
            name: vol-sqldump
      
      containers: 
        - env: 
            - name: MYSQL_ROOT_PASSWORD
              value: drupal8
            - name: MYSQL_DATABASE
              value: drupal8
            - name: MYSQL_USER
              value: drupal8
            - name: MYSQL_PASSWORD
              value: drupal8
          
          image: mariadb:10.5.4
          name: d8-mariadb
          
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
              
          volumeMounts: 
            - mountPath: /var/lib/mysql
              name: vol-mariadb
              subPath: dbdata
              
            - mountPath: /docker-entrypoint-initdb
              name: vol-sqldump
            
      volumes:
      
        - name: vol-mariadb
          persistentVolumeClaim: 
            claimName: pvc-mariadb
            
        - name: vol-sqldump
          persistentVolumeClaim: 
            claimName: pvc-sqldump
  
